export type CategoriaKardexTab =
  | 'PRODUCTO_TERMINADO'
  | 'MATERIA_PRIMA'
  | 'INSUMO'
  | 'ENVASE'
  | 'EMBALAJE';

export interface KardexMovimientoUI {
  id: string;
  categoriaKardex: CategoriaKardexTab;
  productoNombre: string;
  familia: string;
  categoriaNombre: string;
  proveedorCliente: string;
  unidadMedida: string;
  fecha: string;
  tipoDoc: string;
  serie: string;
  numero: string;
  otp: string;
  tipoOperacion: string;
  cantidadEntrada: number;
  cantidadSalida: number;
  saldoFinal: number;
}

export const KARDEX_REAL_SEED_DATA: KardexMovimientoUI[] = [
  // ── 1. PRODUCTO TERMINADO ──
  {
    id: 'kdx-pt-001',
    categoriaKardex: 'PRODUCTO_TERMINADO',
    productoNombre: 'Crema Muscular Mentolada 1KG',
    familia: 'Cosmética & Cuidado Personal',
    categoriaNombre: 'Línea Muscular Tópica',
    proveedorCliente: 'Farmacias Peruanas S.A.C.',
    unidadMedida: 'UN F0 (1 KG)',
    fecha: '2026-08-01',
    tipoDoc: 'FACTURA',
    serie: 'F001',
    numero: '0008412',
    otp: 'LOT-2024-0841',
    tipoOperacion: 'ENTRADA PRODUCCIÓN',
    cantidadEntrada: 128,
    cantidadSalida: 0,
    saldoFinal: 128,
  },
  {
    id: 'kdx-pt-002',
    categoriaKardex: 'PRODUCTO_TERMINADO',
    productoNombre: 'Serum de Salmón Alfalion 30ML',
    familia: 'Cosmética Facial Avanzada',
    categoriaNombre: 'Serum Anti-Edad',
    proveedorCliente: 'Alfalion Corp. S.A.',
    unidadMedida: 'UN F0 (30 ML)',
    fecha: '2026-08-02',
    tipoDoc: 'GUIA REMISION',
    serie: 'T001',
    numero: '0003120',
    otp: 'LOT-2024-0842',
    tipoOperacion: 'ENTRADA PRODUCCIÓN',
    cantidadEntrada: 1000,
    cantidadSalida: 0,
    saldoFinal: 1000,
  },
  {
    id: 'kdx-pt-003',
    categoriaKardex: 'PRODUCTO_TERMINADO',
    productoNombre: 'Shampoo de Batana Orgánico 500ML',
    familia: 'Cuidado Capilar Natural',
    categoriaNombre: 'Shampoo Reestructurante',
    proveedorCliente: 'Austin Cosmetics Perú',
    unidadMedida: 'UN F0 (500 ML)',
    fecha: '2026-08-03',
    tipoDoc: 'FACTURA',
    serie: 'F001',
    numero: '0008430',
    otp: 'LOT-2024-0843',
    tipoOperacion: 'ENTRADA PRODUCCIÓN',
    cantidadEntrada: 500,
    cantidadSalida: 0,
    saldoFinal: 500,
  },
  {
    id: 'kdx-pt-004',
    categoriaKardex: 'PRODUCTO_TERMINADO',
    productoNombre: 'Crema Cúrcuma & Mentol Industrial 250KG',
    familia: 'Línea Magistral & Masiva',
    categoriaNombre: 'Crema Tópica Antiinflamatoria',
    proveedorCliente: 'Geyma Biotech S.A.C.',
    unidadMedida: 'KG',
    fecha: '2026-08-04',
    tipoDoc: 'GUIA REMISION',
    serie: 'T001',
    numero: '0003125',
    otp: 'LOT-2024-0840',
    tipoOperacion: 'ENTRADA PRODUCCIÓN',
    cantidadEntrada: 250,
    cantidadSalida: 0,
    saldoFinal: 250,
  },
  {
    id: 'kdx-pt-005',
    categoriaKardex: 'PRODUCTO_TERMINADO',
    productoNombre: 'Detergente Líquido Concentrado Floral 20L',
    familia: 'Limpieza & Desinfección Industrial',
    categoriaNombre: 'Detergentes Industriales',
    proveedorCliente: 'Clínica San Borja S.A.',
    unidadMedida: 'BIDÓN (20 L)',
    fecha: '2026-08-05',
    tipoDoc: 'FACTURA',
    serie: 'F001',
    numero: '0008455',
    otp: 'LOT-2024-0845',
    tipoOperacion: 'DESPACHO CLIENTE',
    cantidadEntrada: 0,
    cantidadSalida: 45,
    saldoFinal: 180,
  },

  // ── 2. MATERIA PRIMA ──
  {
    id: 'kdx-mp-001',
    categoriaKardex: 'MATERIA_PRIMA',
    productoNombre: 'Soda Cáustica Escamas 99%',
    familia: 'Insumos Químicos Básicos',
    categoriaNombre: 'Álcalis & Bases Fuertes',
    proveedorCliente: 'Química Suiza S.A.C.',
    unidadMedida: 'KG',
    fecha: '2026-07-28',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP02',
    numero: '0041289',
    otp: 'ING-2026-0120',
    tipoOperacion: 'COMPRA MATERIA PRIMA',
    cantidadEntrada: 500,
    cantidadSalida: 0,
    saldoFinal: 1250,
  },
  {
    id: 'kdx-mp-002',
    categoriaKardex: 'MATERIA_PRIMA',
    productoNombre: 'Ácido Sulfónico Lineal 96% (LABS)',
    familia: 'Tensioactivos Aniónicos',
    categoriaNombre: 'Surfactantes Industriales',
    proveedorCliente: 'Insuquímica del Perú S.A.',
    unidadMedida: 'KG',
    fecha: '2026-07-29',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP01',
    numero: '0019280',
    otp: 'ING-2026-0121',
    tipoOperacion: 'COMPRA MATERIA PRIMA',
    cantidadEntrada: 1000,
    cantidadSalida: 0,
    saldoFinal: 2400,
  },
  {
    id: 'kdx-mp-003',
    categoriaKardex: 'MATERIA_PRIMA',
    productoNombre: 'Alcohol Isopropílico 99.8% USP',
    familia: 'Solventes & Alcoholes USP',
    categoriaNombre: 'Solventes Orgánicos',
    proveedorCliente: 'Solventes & Derivados Perú',
    unidadMedida: 'L',
    fecha: '2026-07-30',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP03',
    numero: '0098412',
    otp: 'ING-2026-0122',
    tipoOperacion: 'CONSUMO EN REACTOR R-01',
    cantidadEntrada: 0,
    cantidadSalida: 120,
    saldoFinal: 880,
  },
  {
    id: 'kdx-mp-004',
    categoriaKardex: 'MATERIA_PRIMA',
    productoNombre: 'Glicerina Vegetal USP 99.5%',
    familia: 'Humectantes & Emolientes',
    categoriaNombre: 'Polialcoholes USP',
    proveedorCliente: 'OleoSur Perú S.A.C.',
    unidadMedida: 'KG',
    fecha: '2026-08-01',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP02',
    numero: '0041300',
    otp: 'ING-2026-0125',
    tipoOperacion: 'COMPRA MATERIA PRIMA',
    cantidadEntrada: 600,
    cantidadSalida: 0,
    saldoFinal: 1450,
  },
  {
    id: 'kdx-mp-005',
    categoriaKardex: 'MATERIA_PRIMA',
    productoNombre: 'Mentol Cristalino USP',
    familia: 'Extractos & Principios Activos',
    categoriaNombre: 'Terpenos Tópicos',
    proveedorCliente: 'Aromas & Químicos Andinos',
    unidadMedida: 'KG',
    fecha: '2026-08-02',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP01',
    numero: '0019310',
    otp: 'ING-2026-0128',
    tipoOperacion: 'CONSUMO EN REACTOR R-02',
    cantidadEntrada: 0,
    cantidadSalida: 24,
    saldoFinal: 142,
  },

  // ── 3. INSUMO ──
  {
    id: 'kdx-ins-001',
    categoriaKardex: 'INSUMO',
    productoNombre: 'Lauril Éter Sulfato de Sodio 70% (LESS)',
    familia: 'Tensioactivos Principales',
    categoriaNombre: 'Bases Espumantes',
    proveedorCliente: 'Insuquímica del Perú S.A.',
    unidadMedida: 'KG',
    fecha: '2026-07-29',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP01',
    numero: '0019285',
    otp: 'ING-2026-0123',
    tipoOperacion: 'COMPRA INSUMO',
    cantidadEntrada: 1200,
    cantidadSalida: 0,
    saldoFinal: 3100,
  },
  {
    id: 'kdx-ins-002',
    categoriaKardex: 'INSUMO',
    productoNombre: 'Fragancia Lavanda Francesa Concentrada',
    familia: 'Fragancias & Aromas Industriales',
    categoriaNombre: 'Esencias Cosméticas',
    proveedorCliente: 'Sensient Fragrances Perú',
    unidadMedida: 'L',
    fecha: '2026-07-31',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP04',
    numero: '0005120',
    otp: 'ING-2026-0126',
    tipoOperacion: 'CONSUMO EN MEZCLADOR M-01',
    cantidadEntrada: 0,
    cantidadSalida: 15,
    saldoFinal: 85,
  },
  {
    id: 'kdx-ins-003',
    categoriaKardex: 'INSUMO',
    productoNombre: 'Colorante Azul Brillante CI 42090',
    familia: 'Colorantes & Pigmentos',
    categoriaNombre: 'Colorantes Cosméticos',
    proveedorCliente: 'ColorChem S.A.C.',
    unidadMedida: 'KG',
    fecha: '2026-08-01',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP01',
    numero: '0019302',
    otp: 'ING-2026-0127',
    tipoOperacion: 'COMPRA INSUMO',
    cantidadEntrada: 25,
    cantidadSalida: 0,
    saldoFinal: 62,
  },
  {
    id: 'kdx-ins-004',
    categoriaKardex: 'INSUMO',
    productoNombre: 'Conservante DMDM Hidantoína + IPBC',
    familia: 'Preservantes & Biocidas',
    categoriaNombre: 'Conservantes de Amplio Espectro',
    proveedorCliente: 'BioPreserv Perú',
    unidadMedida: 'KG',
    fecha: '2026-08-03',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP02',
    numero: '0041315',
    otp: 'ING-2026-0130',
    tipoOperacion: 'CONSUMO PRODUCCIÓN',
    cantidadEntrada: 0,
    cantidadSalida: 8,
    saldoFinal: 92,
  },

  // ── 4. ENVASE ──
  {
    id: 'kdx-env-001',
    categoriaKardex: 'ENVASE',
    productoNombre: 'Bidón PEAD 20L Boca Ancha Blanco',
    familia: 'Envases Plásticos Rígidos',
    categoriaNombre: 'Bidones Industriales',
    proveedorCliente: 'Plásticos Industriales Lima S.A.C.',
    unidadMedida: 'UN',
    fecha: '2026-07-28',
    tipoDoc: 'GUIA REMISION',
    serie: 'T002',
    numero: '0089123',
    otp: 'ING-2026-0119',
    tipoOperacion: 'COMPRA ENVASES',
    cantidadEntrada: 500,
    cantidadSalida: 0,
    saldoFinal: 850,
  },
  {
    id: 'kdx-env-002',
    categoriaKardex: 'ENVASE',
    productoNombre: 'Frasco Ámbar Cóncavo 30ML con Gotero',
    familia: 'Envases de Vidrio Farmacéutico',
    categoriaNombre: 'Frascos Cosméticos',
    proveedorCliente: 'Vidrios del Pacífico S.A.',
    unidadMedida: 'UN',
    fecha: '2026-07-30',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP01',
    numero: '0019290',
    otp: 'ING-2026-0124',
    tipoOperacion: 'ENVASADO LOTE 0842',
    cantidadEntrada: 0,
    cantidadSalida: 1000,
    saldoFinal: 2500,
  },
  {
    id: 'kdx-env-003',
    categoriaKardex: 'ENVASE',
    productoNombre: 'Pote Cosmético 1KG Blanco con Tapa Precinto',
    familia: 'Envases Plásticos Inyectados',
    categoriaNombre: 'Potes Cosméticos',
    proveedorCliente: 'Plásticos Industriales Lima S.A.C.',
    unidadMedida: 'UN',
    fecha: '2026-08-02',
    tipoDoc: 'GUIA REMISION',
    serie: 'T002',
    numero: '0089140',
    otp: 'ING-2026-0129',
    tipoOperacion: 'ENVASADO LOTE 0841',
    cantidadEntrada: 0,
    cantidadSalida: 128,
    saldoFinal: 1150,
  },

  // ── 5. EMBALAJE ──
  {
    id: 'kdx-emb-001',
    categoriaKardex: 'EMBALAJE',
    productoNombre: 'Caja Cartón Corrugado Doble Onda 40x30x30',
    familia: 'Embalajes de Cartón',
    categoriaNombre: 'Cajas de Despacho',
    proveedorCliente: 'Cartonería Nacional S.A.C.',
    unidadMedida: 'UN',
    fecha: '2026-07-29',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP03',
    numero: '0003412',
    otp: 'ING-2026-0122',
    tipoOperacion: 'COMPRA EMBALAJES',
    cantidadEntrada: 400,
    cantidadSalida: 0,
    saldoFinal: 750,
  },
  {
    id: 'kdx-emb-002',
    categoriaKardex: 'EMBALAJE',
    productoNombre: 'Parihuela Madera Tratada NIMF-15 (1.20 x 1.00m)',
    familia: 'Palets & Parihuelas',
    categoriaNombre: 'Palets de Exportación',
    proveedorCliente: 'Maderas del Centro E.I.R.L.',
    unidadMedida: 'UN',
    fecha: '2026-08-01',
    tipoDoc: 'GUIA REMISION',
    serie: 'T001',
    numero: '0012450',
    otp: 'ING-2026-0125',
    tipoOperacion: 'DESPACHO LOGÍSTICO',
    cantidadEntrada: 0,
    cantidadSalida: 12,
    saldoFinal: 68,
  },
  {
    id: 'kdx-emb-003',
    categoriaKardex: 'EMBALAJE',
    productoNombre: 'Cinta Embalaje Industrial 2" x 100m Transparente',
    familia: 'Cintas & Adhesivos Industriales',
    categoriaNombre: 'Cintas de Embalar',
    proveedorCliente: 'Adhesivos Peruanos S.A.',
    unidadMedida: 'ROLLO',
    fecha: '2026-08-04',
    tipoDoc: 'FACTURA PROVEEDOR',
    serie: 'FP02',
    numero: '0021480',
    otp: 'ING-2026-0131',
    tipoOperacion: 'COMPRA EMBALAJES',
    cantidadEntrada: 120,
    cantidadSalida: 0,
    saldoFinal: 240,
  },
];
